### ISSUE TITLE
Configuring sam2 environment on Linux system

### ISSUE THREAD

**Issue by dehaozhou** [facebookresearch/segment-anything-2#108]
Firstly, you need to use the nvcc -V command to confirm your CUDA version. Please ensure that the CUDA version is 12.1 or higher.
conda create --name sam2 python==3.10
conda activate sam2
pip3 install torch torchvision torchaudio
Be careful not to specify the version, as automatically installed versions will match each other.
pip install --no-build-isolation -e .
pip install -e ".[demo]"
Installation successful.
Note: Ensure that your CUDA environment variables are set at the bottom of the .bashrc file, otherwise, you may encounter unexpected errors.

**Comment by ronghanghu** [comment]
Hi, this is likely due to a failure in SAM 2 CUDA extension building. We have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).
