### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by RodneyHe** [facebookresearch/segment-anything-2#135]
Hi, is there a method can compile SAM 2 in the nvidia driver with old version? My project is deployed in cluster, the gpu driver version is fixed (gpu driver version 470.74; cuda driver version 11.4; cuda runtime version 11.6), I tried to update the cuda runtime version to 12.1 and install corresponding pytorch 2.3, but it doesn't work, still got issue of old nvidia driver version.

**Comment by ronghanghu** [comment]
Hi, this is likely due to a failure in SAM 2 CUDA extension building. We have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).
