### ISSUE TITLE
Displays a warning when starting

### ISSUE THREAD

**Issue by alex13by** [facebookresearch/segment-anything-2#136]
D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2\modeling\sam\transformer.py:20: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()

**Comment by ronghanghu** [comment]
Hi, this is likely because you have an old GPU that doesn't support Flash Attention. If the image or video prediction works for you, you can ignore this warning.

If there is an error, we have recently added fallback to all available kernels (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem. You can pull the latest code via `git pull`, which should resolve the error.

**Comment by RafaPolit** [comment]
Good evening.  I have a 3080ti which should allow this, but I am getting this same error:
```
[...]\ComfyUI-segment-anything-2\sam2\modeling\sam\transformer.py:20: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
```

**Comment by FBalemba** [comment]
im getting the same error:
```
[...]ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2\modeling\sam\transformer.py:20: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
```

**Comment by DarkAlchy** [comment]
Heck, I have a 4090 with this. :(
