### ISSUE TITLE
About Cuda Error

### ISSUE THREAD

**Issue by wuqun-tju** [facebookresearch/segment-anything-2#144]
When I run "video_predictor_example.py", there is a problem as follow:

RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by ronghanghu** [comment]
Hi, this is likely due to an error in building the SAM 2 CUDA extension. We have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).
