### ISSUE TITLE
Is it possible to use existing masks as prompts for video tracking?

### ISSUE THREAD

**Issue by MaxTeselkin** [facebookresearch/segment-anything-2#164]
Hi, thanks for open-sourcing great work!

I am curious if it is possible to use SAM2 as first-frame-given mask tracker for videos (like XMem, for example)? I mean the case when masks were not created by SAM2, is it possible to track such masks?

**Comment by ShuoShenDe** [comment]
Hi dear Max,
I think it is completely possible. Because the mask formate they used are same. What I created is a repository, that could Segmente images by sam1 and tracking by sam2, which works very well.

> Hi, thanks for open-sourcing great work!
> 
> I am curious if it is possible to use SAM2 as first-frame-given mask tracker for videos (like XMem, for example)? I mean the case when masks were not created by SAM2, is it possible to track such masks?

**Comment by ronghanghu** [comment]
Hi, @MaxTeselkin @ShuoShenDe SAM 2 also allows tracking in videos based on points, box, or *mask* prompts. Note that you don't need XMem in this case, since SAM 2 itself can handle object segmentation and tracking in videos (in addition to static images).

For mask prompts, it can be added to SAM 2 via the `add_new_mask method` in the `SAM2VideoPredictor` class.

Examples for adding point, box or mask prompts in SAM 2 can be seen in
* [video_predictor_example.ipynb](https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/video_predictor_example.ipynb)
* [tools/vos_inference.py](https://github.com/facebookresearch/segment-anything-2/blob/main/tools/vos_inference.py) for an example).

**Comment by MaxTeselkin** [comment]
@ronghanghu Thanks for clarifying
