### ISSUE TITLE
Question about box input

### ISSUE THREAD

**Issue by z-jiaming** [facebookresearch/segment-anything-2#182]
@ronghanghu Thanks for your commit about "[Add interface for box prompt in SAM 2 video predictor".
We took a closer look at the code and found a problem that confused us.

In SAM1, PromptEncoder encodes box inputs with def _embed_boxes() and pad the def _embed_points() if boxes are None.
But in SAM2, if we're not mistaken, SAM2VideoPredictor first concates box input with point input and set boxes=None, thus the pad will necessarily be True even if we really input boxes. 

I would like to understand why this modification was made?

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/c4db46e0-a110-4041-bb44-4820f78a5492">
 
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/715f797c-e060-4c89-8b7e-72eab2f37865">

**Comment by ronghanghu** [comment]
Hi @z-jiaming, this is mostly an implementation detail in SAM 2. When building the model, we found it easier to handle boxes and points via the same `points` input (since boxes are just represented as two points after all), which also resulted in an extra padding even when the boxes are provided, as you mentioned above. This modification has no performance impact and is mainly about simplifying the prompt format during our development.

**Comment by z-jiaming** [comment]
Thanks for your quick reply!
BTW, I still wonder about the extra padding and would like to know the reasons and considerations.
