### ISSUE TITLE
There may be some bugs for the function "get_connected_components" in utils\misc.py?

### ISSUE THREAD

**Issue by zhangxin06** [facebookresearch/segment-anything-2#200]
When I call this function, the following error occurs, and  I find that none of the later cuda-related operations can be performed.

![Snipaste_2024-08-12_09-10-13](https://github.com/user-attachments/assets/b9c5fd36-6e02-47ac-bec9-26ba385b0fb4)

**Comment by ronghanghu** [comment]
Hi, this is likely due to an error in building the SAM 2 CUDA extension, leading to the error above that prevents `get_connected_components` from working. From the error message, it seems that the CUDA kernel is somehow not compiled towards your GPU capability (as mentioned in https://developer.nvidia.com/cuda-gpus).

Maybe you can try running the following via `TORCH_CUDA_ARCH_LIST=9.0 8.0 8.6 8.9 7.0 7.2 6.0` to manually specify the CUDA capability version?
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
TORCH_CUDA_ARCH_LIST="9.0 8.0 8.6 8.9 7.0 7.2 6.0" \
pip install -e ".[demo]"
```

In case it still doesn't work, you may remove the line `"++model.fill_hole_area=8"` in https://github.com/facebookresearch/segment-anything-2/blob/778e1127404547429b281d9c9394ddb3652b85a5/sam2/build_sam.py#L64 to turn off this post-processing step that calls into `get_connected_components`.

---

Also, we have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155 and https://github.com/facebookresearch/segment-anything-2/pull/175) as a workaround to this problem.

Now we allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).
