### ISSUE TITLE
CPU usage in propagate_in_video

### ISSUE THREAD

**Issue by voslartomas** [facebookresearch/segment-anything-2#221]
Hello, I noticed that when running propagate_in_video function script is using single CPU and it's at 100% all the time. Is this expected behavior?

Reason I am asking is that I am trying to deploy service which is using SAM2 into AWS, starting now with g4d instances and it is quite slow, so I am trying to find bottlenecks.

**Comment by heyoeyo** [comment]
> using single CPU

This seems unusual. If you have other libraries installed that use pytorch, it may be that they're limiting cpu use...? You can change the number of cpus to, say 4, by using: `torch.set_num_threads(4)`, though if some other library is setting it back to 1 elsewhere, you may need to repeatedly call this before processing each frame.

**Comment by voslartomas** [comment]
I've tried to set number of threads like this `torch.set_num_threads(multiprocessing.cpu_count())` but still the same.

![Screenshot from 2024-08-14 16-36-12](https://github.com/user-attachments/assets/2a8c5cb0-162b-45fe-b071-05d260cdb577)

**Comment by heyoeyo** [comment]
Yes it's possible gunicorn would interfere with things, I'm not that familiar with it but I believe it's used to distribute the server across cpu cores and maybe that has a limiting effect...

A simple way to test this would be to run a copy of the video processing outside of the server process (i.e. manually run in a different script), and see if that uses more cpu. Here's a minimal example (assuming you have the example 'bedroom' video data on the file system):
```python
import numpy as np
from sam2.build_sam import build_sam2_video_predictor

vid_folder_path = "notebooks/videos/bedroom"
sam2_checkpoint = "checkpoints/sam2_hiera_tiny.pt"
model_cfg = "sam2_hiera_t.yaml"
predictor = build_sam2_video_predictor(model_cfg, sam2_checkpoint, device="cpu")
inference_state = predictor.init_state(video_path=vid_folder_path)

_, out_obj_ids, out_mask_logits = predictor.add_new_points(
    inference_state=inference_state,
    frame_idx=0,
    obj_id=1,
    points=np.array([[210, 350]], dtype=np.float32),
    labels=np.array([1], np.int32),
)

for res in predictor.propagate_in_video(inference_state):
    # Do nothing with video results
    pass
```

I get well over ~600% cpu on htop (6 core cpu) running this (without the set_num_threads call even). Assuming that works on your server, maybe there's some gunicorn setting that can be adjusted or otherwise you might need to run the SAM model in a separate process.

**Comment by voslartomas** [comment]
I am sorry I forgot to mention that I am using device `cuda`, I know it's using graphics card, it's just strange that CPU is also at 100% straight, so it might possibly slowing things down.

Also I was able to improve performance a lot by adding `torch.autocast("cuda", dtype=torch.bfloat16).__enter__()` into propagation function (before I had it only at server start) and that improves performance about 60%.

So 20s video now takes around 30-40s for propagation, but at the same time, it takes around same time to load JPEG frames, is there any way how to improve performance of loading frames?

**Comment by heyoeyo** [comment]
> is there any way how to improve performance of loading frames

There is an `async_loading_frames` inside the [init_state](https://github.com/facebookresearch/segment-anything-2/blob/7e1596c0b6462eb1d1ba7e1492430fed95023598/sam2/sam2_video_predictor.py#L40) function that causes the JPEGs to load while processing frames (instead of the 'load everything first' default approach) which may help? (It doesn't change total timing much for me, but I've only tried it on the short sample data).

Also, the image loading does a [bit of work](https://github.com/facebookresearch/segment-anything-2/blob/7e1596c0b6462eb1d1ba7e1492430fed95023598/sam2/utils/misc.py#L94-L99) (resizing images) on the cpu that could be moved to the gpu, especially if you know in advance that all the frames will be the same size. So modifying that code to load all frames in 'as-is', then move to the gpu to do resizing/reshaping might speed things up?

Otherwise, it might be worth looking at something like [tensorRT](https://github.com/NVIDIA/TensorRT) which may be more efficient at using/feeding the gpu compared to pytorch. I think there are some known issues with pytorch 'wasting' the cpu while waiting for the gpu to finish.

**Comment by voslartomas** [comment]
Thank you for the information!
