### ISSUE TITLE
Is SAM2 really 6 times faster than SAM for image segmentation?

### ISSUE THREAD

**Issue by squashking** [facebookresearch/segment-anything-2#227]
Hi, I have briefly had a look at the introduction of SAM2. If I get it right, it says SAM2 is 6 times faster than SAM when used for image segmentation. But I did a test of segmenting the same image with the same prompts and found SAM2 is actually slower.
I'm comparing SAM using the "vit_h"  model and SAM2 using the "hiera_large" model. Below is the output (I can post my code if necessary). :

Loading time (SAM): 10.890620231628418 seconds
Execution time (SAM): 0.271709680557251 seconds
Loading time (SAM2): 4.8107569217681885 seconds
Execution time (SAM2): 0.4044489860534668 seconds  

In the above, loading time is the time used for loading the model while execution time is the  time for making a prediction. We can see that the time for loading the model has been halved but the time for making a prediction has increased by almost 50%.

Did I misunderstand the introduction about the speed of SAM2 or I make any mistake in coding?
Thank you!

**Comment by heyoeyo** [comment]
Those numbers seem a bit strange (at the execution times). Assuming you're using cuda, you may need to force a [synchronization](https://pytorch.org/docs/stable/generated/torch.cuda.synchronize.html) before recording the times? That can often lead to misleading results otherwise. It's also important to run the model many times, since the first run usually is much slower than repeat runs.

From what I've seen, SAMv2 does seem consistently faster than v1, but I think the 6x faster claim requires very careful cherry-picking of the data.

Specifically, I think they may be comparing either SAMv1-huge (a 2.5GB file) or SAMv1-large (1.2GB) running on float32 vs. SAMv2-large (900MB) running on float16, and the speed up is to do with image encoding only. The prompt + mask decoding is very slightly slower on v2.

Here are the results I get (averaged across 50 runs) for different models/data types:

|Model | Data type | Image encoding time (ms) |
| ------| --------| ---------------------------|
| V1-Huge| float32 | 430 |
| V1-Large | float32 | 244 |
| V2-Large | float32 | 158 |
| V1-Huge | bfloat16 | 165 |
| V1-Large | bfloat16 | 100 |
| V2-Large | bfloat16 | 47 |

So comparing V2-large on float16 vs. V1-large on float32 gives ~5.2x speed up, while comparing to V1-huge w/ float32 gives a 9x speedup. But in more like-for-like comparisons (e.g. comparing the large models on the same data type) it's more like a 2x speed up (still good, but not the claimed 6x).

**Comment by chayryali** [comment]
Yes, SAM 2 really is 6 times faster than SAM for image segmentation. :smiley:

All fps numbers are measured end-to-end (not just image encoding), using the same precision for all models (bfloat16) in a like-for-like and fair comparison - no cherry picking, @heyoeyo.

The _default SAM 2_ model (throughout the paper) is the B+ model, while the _default SAM 1_ model (throughout that paper) is the H-model, the default models are compared in Table 6, shown below

<img width="1115" alt="Screenshot 2024-08-16 at 4 03 50 PM" src="https://github.com/user-attachments/assets/ee2617b1-31e1-40f9-b650-09ac8378d814">

Put another way, if you were to visualize an accuracy vs speed plot, at the same accuracy (actually even better accuracy) as SAM (H), the speed-up is 6x using SAM 2 (B+)

You may be interested in Appendix C.3 where we describe how speed is benchmarked. As @heyoeyo suggested, @squashking you might want to discard a small number of batches to get more reliable numbers. You maybe also be interested in Table 15 which has additional benchmarking.

**Comment by heyoeyo** [comment]
Thanks for clarifying @chayryali, I was thinking picking different sized models counts as cherry-picking, but comparing by matching accuracy makes sense.

And for sake of verification, here's a continuation of the (image encoding) timing I get for the base/tiny models:

| Model	| Data type |	Image encoding time (ms) |
| -----| ----------| ---------------------------|
| V2-base+ | bfloat16 | 22 |
| V2-tiny | bfloat16 | 10 |

Which is consistent with the >6x claim for v2-base+ vs v1-huge.

**Comment by chayryali** [comment]
Similarly sized models from different model families can have quite different speed (e.g. v1-L vs v2-L in your benchmarking above), so such comparison is not super useful. And size is anyway often just a (bad) proxy for speed (what we often actually care about).  

Thanks for the verification!

**Comment by squashking** [comment]
Thank you @chayryali  and @heyoeyo , but I'm still not sure why I got the opposite results. As I said, I was comparing SAM1( "vit_h" model) and SAM2 ( "hiera_large" ) for segmenting exactly the same image, I guess I have to post my code for clarification:

```
import torch
import numpy as np
import cv2
from PIL import Image
from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor

from segment_anything import sam_model_registry, SamAutomaticMaskGenerator, SamPredictor

import time

import hydra

New_SAM = False

# use bfloat16 for the entire notebook
if New_SAM:
    torch.autocast(device_type="cuda", dtype=torch.bfloat16).__enter__()

# image = Image.open('/home/taohu/Projects/Data/RGB/thumbnail_Picture1.png')
# image = np.array(image.convert("RGB"))

image = cv2.imread('/home/taohu/Projects/Data/RGB/thumbnail_Picture1.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


if New_SAM:
    method = "SAM2"
else:
    method = "SAM1"

start_time1 = time.time()

if New_SAM:
    sam2_checkpoint = "models/sam2_hiera_large.pt"
    model_cfg = "sam2_hiera_l.yaml"

    # hydra is initialized on import of sam2, which sets the search path which can't be modified
    # so we need to clear the hydra instance
    hydra.core.global_hydra.GlobalHydra.instance().clear()
    # reinit hydra with a new search path for configs
    hydra.initialize_config_module('sam2_configs', version_base='1.2')
    sam2_model = build_sam2(model_cfg, sam2_checkpoint, device="cuda")

    predictor = SAM2ImagePredictor(sam2_model)
    predictor.set_image(image)
else:
    model_type = "vit_h"
    sam_checkpoint = "models/sam_vit_h_4b8939.pth"          
    sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
    sam.to("cuda")
    predictor = SamPredictor(sam)
    predictor.set_image(image)

end_time1 = time.time()
load_time = end_time1 - start_time1
print(f"Loading time ({method}): {load_time} seconds")

input_box = np.array([58,107, 213,281])
input_point = np.array([[104, 163]])
input_label = np.array([1])

start_time2 = time.time()

masks, scores, logits = predictor.predict(
    point_coords=input_point,
    point_labels=input_label,
    box=input_box,
    multimask_output=False,
)

end_time2 = time.time()
execution_time = end_time2 - start_time2
print(f"Execution time ({method}): {execution_time} seconds")

mask_array = np.array(masks[0]) 

if New_SAM:
    mask_array = mask_array.astype(np.uint8)*255 # SAM2 use 0~1 values for the mask
    mask_image = Image.fromarray(mask_array)
    mask_image.save("sam2-bw.jpg")
else:
    mask_image = Image.fromarray(mask_array)
    mask_image.save("sam1-bw.jpg")
```
So I ran the above code twice, the first time I set "New_SAM" to False (which means using SAM1), and the second time I set it to True (which means using SAM2). And I got the results:

Loading time (SAM1): 10.890620231628418 seconds
Execution time (SAM1): 0.271709680557251 seconds
Loading time (SAM2): 4.8107569217681885 seconds
Execution time (SAM2): 0.4044489860534668 seconds

I was running with CUDA. My GPU was RTX 4060 Ti.
The above results showed the SAM2 is almost 50% slower than SAM1 in making a prediction. Can you please check if  made any mistake in my code? Thank you!

**Comment by heyoeyo** [comment]
@squashking I think the issue is that the image encoder is running within the 'loading' timed block.
More specifically it's the line:
```python
predictor.set_image(image)
```

The image encoder is the bulk of the SAM model execution time, so if you move that into the execution time block, I think that should give the expected timing results.

As for why your numbers consistently show SAMv2 being ~50% slower than SAMv1 when timing the `predict` function. That function runs the prompt + mask decoder, and the mask decoder really is going to be consistently slower on v2, due to having some extra steps compared to v1.

**Comment by squashking** [comment]
@heyoeyo Thank you for the explanation. I do find that after moving "set_image" to the execution time block the speed of SAM2 is 3 times (a bit less) than SAM1:

Loading time (SAM1): 9.282342672348022 seconds
Execution time (SAM1): 1.4434857368469238 seconds
Loading time (SAM2): 4.7463905811309814 seconds
Execution time (SAM2): 0.4952991008758545 seconds

I think under some circumstances the time for making a prediction (or inference) is more important than the time for image encoder.  For example, suppose I need to repeatedly update the prompts to generate the desired mask, in this case "set_image" just need to run once but "predictor.predict" needs to run multiple times, so in the end SAM2 could actually takes more time than SAM1.

**Comment by heyoeyo** [comment]
> ... "predictor.predict" needs to run multiple times, so in the end SAM2 could actually takes more time than SAM1

Yes that's a good point! Though the prompt + mask decoder runs quite fast compared to the image encoder, in most cases I think it would take dozens of re-runs of the decoder before it takes more total time than the one-time image encoding (this can happen extremely quickly using the model interactively to be fair).

Oddly though, your updated numbers suggest the decoder is running very slowly. SAM2 was 0.404s with only the "predictor.predict" and then 0.495s after including "set_image", which suggests that "set image" takes ~100ms and "predict" takes ~400ms. It might be worth running the predictor twice and timing only the second run just to double check this, because it should be much faster, something like:
```python
input_box = np.array([58,107, 213,281])
input_point = np.array([[104, 163]])
input_label = np.array([1])

# Run once as a 'warm-up' just to rule out initial loading effects
masks, scores, logits = predictor.predict(
    point_coords=input_point,
    point_labels=input_label,
    box=input_box,
    multimask_output=False,
)

# Run a second time with timing
start_time2 = time.time()
masks, scores, logits = predictor.predict(
    point_coords=input_point,
    point_labels=input_label,
    box=input_box,
    multimask_output=False,
)
end_time2 = time.time()
execution_time = end_time2 - start_time2
print(f"Execution time ({method}): {execution_time} seconds")
```
I think you should find the decoder runs well under 400ms (I find it only takes ~20ms on _CPU_ for example)

**Comment by squashking** [comment]
@heyoeyo  You are right  the decoding time is negligible compared to the encoding time. The two results above were from different runs - you cannot simply do the subtraction, because the counted time fluctuates each time I run the code. Now, I have modified the code a bit by printing the time for the encoder and decoder separately and following your advice to run 'predict' twice. Below are the results:

Loading time (SAM1): 9.20648717880249 seconds
Encoder time (SAM1): 1.1701500415802002 seconds
Prediction time (SAM1): 0.008125543594360352 seconds

Loading time (SAM2): 4.628658056259155 seconds
Encoder time (SAM2): 0.09668612480163574 seconds
Prediction time (SAM2): 0.011764764785766602 seconds 

I can see the time for the encoder has reduced by 12 times, while the prediction time goes up by 50%. You are right the prediction time is well below 400 ms.

**Comment by jaredm5991** [comment]
Hi @squashking,
great results. Can you also please share the code for these results? Thanks a lot!

**Comment by heyoeyo** [comment]
@squashking Those SAMv2 results look more like what I would expect. The SAMv1 result is surprisingly slow still (at least the image encoder part). In case that matters, I believe part of the reason the bfloat16 code near the top of your script:
```python
if New_SAM:
    torch.autocast(device_type="cuda", dtype=torch.bfloat16).__enter__()
```

This probably means that SAMv1 is using float32. If v1 is made to also use bfloat16, I think the encoder time would drop by ~50% (e.g. it would be closer to 0.5s rather than >1s), though if I remember correctly, SAMv1 may require some (minor) changes to work properly with float16.

**Comment by squashking** [comment]
@heyoeyo If I use bfloat16 also for SAM1, I will get error: TypeError: Got unsupported ScalarType BFloat16
Can you tell me how to do minor changes to make it work? Thank you!

**Comment by heyoeyo** [comment]
> Can you tell me how to do minor changes to make it work? 

It's been a long time since I looked at it, so I don't remember the exact changes... Though I think it's mainly a matter of either (a) changing to float32 temporarily to do certain calculations that aren't supported when using bfloat16 ([SAMv2 has examples of this](https://github.com/facebookresearch/segment-anything-2/blob/7e1596c0b6462eb1d1ba7e1492430fed95023598/sam2/modeling/sam2_base.py#L364-L372)) or (b) there are parts of v1 that hard-code the `dtype` of some values to float32 and that causes issues when bfloat16 data is used, so the solution is just to make sure the `dtype` is set to match the incoming data.
The easiest way to make these changes is to run the model with bfloat16 to get an error message which will generally tell you the script/line number where the hard-coded dtype will need to be fixed. You can make those changes, then re-run the model and fix the next dtype error and so on until it runs without any problems.

Alternatively, I have a [repo](https://github.com/heyoeyo/muggled_sam) that supports v1 & v2 models using float32 or bfloat16. The repo includes a [benchmarking](https://github.com/heyoeyo/muggled_sam/blob/main/simple_examples/speed_benchmarking.py) script (the same thing I used for the numbers I posted earlier) that you can use/modify to check the model speeds (just make sure to [change the path](https://github.com/heyoeyo/muggled_sam/blob/61452fc6b53cc334752dc4bbb328cc0e9c01cc49/simple_examples/speed_benchmarking.py#L23) to point at the model file you want to test). The one caveat is that the loading times won't be the same (they'll be slower) due to extra loading/automatic config checks that the original code doesn't perform.

**Comment by squashking** [comment]
@heyoeyo  Thank you! Nice repo. I'll give it a try.
