### ISSUE TITLE
jupyter kernel died

### ISSUE THREAD

**Issue by zjuzhk** [facebookresearch/segment-anything-2#247]
I was running segment-anything-2/notebooks/video_predictor_example.ipynb till the block :

inference_state = predictor.init_state(video_path=video_dir)
frame loading (JPEG): 100%|████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:06<00:00, 30.70it/s]

then the kernel is killed, with the message:
Kernel Restarting
The kernel for segment-anything-2/notebooks/video_predictor_example.ipynb appears to have died. It will restart automatically.

I would appreciate any help.

**Comment by omerone** [comment]
happend to me too when i run it in a docker and it is crushed when i run predictor = SAM2ImagePredictor(sam2_model)

**Comment by heyoeyo** [comment]
Are there any other error messages in the console/terminal before the notebook crashes? That would probably help to pinpoint what caused the error.
If you're using a GPU, my guess would be that it's a VRAM problem. You can try switching to using 'cpu' as your device and see if that avoids the problem. If it does, then you might be able to use the GPU if you add `offload_video_to_cpu=True` when calling the [init_state](https://github.com/facebookresearch/segment-anything-2/blob/7e1596c0b6462eb1d1ba7e1492430fed95023598/sam2/sam2_video_predictor.py#L43) function.

> when i run it in a docker

Docker can introduce another set of complications (if using GPU), it's probably easiest to check that things run outside of it first. If it works outside, then the problem is likely the docker image missing some (cuda) dependencies and/or GPU pass-thru support on the host machine.

**Comment by omerone** [comment]
for me it crushed without any previous error, it shows me a small jupyter window that says it crushed
and i run it locally and it work and also i run it on google collab pro with higher GPU and it worked there as well 
only when i run it on the server of my campus it crushed tried to switch to cpu and didnt work

**Comment by heyoeyo** [comment]
If it doesn't work even with cpu, then it may even be a system RAM limitation. In any case, it's hard to say since there's probably lots of things that could cause jupyter to fail. If possible, it's best to try to get a more descriptive error message by running the code outside of a notebook. Here's a minimal video example (assuming the sample video + tiny model will produce an error):

```python
import numpy as np
from sam2.build_sam import build_sam2_video_predictor

video_folder_path = "notebooks/videos/bedroom"
cfg, ckpt = "sam2_hiera_t.yaml", "checkpoints/sam2_hiera_tiny.pt"
device = "cpu" # or "cuda"
predictor = build_sam2_video_predictor(cfg, ckpt, device=device)
inference_state = predictor.init_state(video_path=video_folder_path)

_, out_obj_ids, out_mask_logits = predictor.add_new_points(
    inference_state=inference_state,
    frame_idx=0,
    obj_id=1,
    points=np.array([[210, 350]], dtype=np.float32),
    labels=np.array([1], np.int32),
)

for res in predictor.propagate_in_video(inference_state):
    # Do nothing with video results
    pass
```
If you run this or something similar as a standalone python script (i.e. not inside jupyter), it will hopefully print out a more detailed error message that could help explain what's going wrong.

**Comment by zjuzhk** [comment]
I switched to the CPU device and it ran smoothly. When I switched back to the CUDA device and executed the Python script, I encountered a version mismatch issue between PyTorch and cuDNN. The problem has now been resolved, thanks to your assistance!
