### ISSUE TITLE
RuntimeError: No available kernel. Aborting execution.

### ISSUE THREAD

**Issue by johntangxia** [facebookresearch/segment-anything-2#65]
run “automatic_mask_generator_example.ipynb”,  
execute this line : masks = mask_generator.generate(image)
RuntimeError: No available kernel. Aborting execution.

**Comment by m-gasiorek** [comment]
You need to install newest pytorch (nightly) sauce it have support of cudnn 9.*

**Comment by forensicmike** [comment]
> You need to install newest pytorch (nightly) because it have support of cudnn 9.*

i'm assuming this means you need to manually install cudnn 9+ as well?

**Comment by m-gasiorek** [comment]
> > You need to install newest pytorch (nightly) because it have support of cudnn 9.*
> 
> i'm assuming this means you need to manually install cudnn 9+ as well?

`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124`

**Comment by forensicmike** [comment]
the solution in #48 worked: https://github.com/facebookresearch/segment-anything-2/issues/48#issuecomment-2259557844

**Comment by ronghanghu** [comment]
Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.

Regarding this error:

This is probably because your machine doesn't have a GPU or a compatible PyTorch version for Flash Attention (see also https://discuss.pytorch.org/t/using-f-scaled-dot-product-attention-gives-the-error-runtimeerror-no-available-kernel-aborting-execution/180900 for a discussion in PyTorch forum). You may be able to resolve this error by replacing the line
```python
OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
```
in [`sam2/modeling/sam/transformer.py`](sam2/modeling/sam/transformer.py) with
```python
OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = True, True, True
```
to relax the attention kernel setting and use other kernels than Flash Attention.
